### ISSUE TITLE
Handle performance intensive input

### ISSUE THREAD

**Issue by basilkar** [RheaMars/zzz-top#6]
Somewhere between `12zzzzzzzzzzzzzzzz` and `12zzzzzzzzzzzzzzzzzzzzz` problems arise :smiling_imp:

**Comment by basilkar** [comment]
Check also `12azzzzazzzzdfgdghdzzzfzb`.

**Comment by RheaMars** [comment]
For me with my 8.0.24 PHP config it ends with: 12zzzzzzzzzzzzzzzzzzzzz

**Comment by basilkar** [comment]
For me, with PHP 8.2.3 (cli), my php.ini reads `memory_limit = -1` (see https://php.net/memory-limit).

**Comment by basilkar** [comment]
Very nice. Now it just fails for inputs like
```12zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz```

**Comment by RheaMars** [comment]
Mir egal.

**Comment by basilkar** [comment]
So, according to [this stackexchange topic](https://stackoverflow.com/questions/670662/whats-the-maximum-value-for-an-int-in-php), we can allow for up to 63 ambiguous `z`'s in the input (because log2(max_integer_in_php) = 63) -- and that's for 64 bit systems.

For bigger numbers we can just render `2^(no_of_ambiguous_characters)` instead of calling `pow` in `getNumberOfAlternatives`.
